In [21]:
import pandas as pd
import re

In [22]:
df = pd.read_json('result.json')

if 'assignments' in df.columns:
    df = pd.json_normalize(df['assignments'])

if 'score' in df.columns:
    df = df[['date', 'teamMemberId', 'shiftTypeId', 'score']]
else:
    df = df[['date', 'teamMemberId', 'shiftTypeId']]

In [23]:
members = df['teamMemberId'].unique()
print(members)

<StringArray>
['tmptf003-0000-0000-0000-000000000008',
 'tmptf002-0000-0000-0000-000000000007',
 'tmptf001-0000-0000-0000-000000000006',
 'tmstf004-0000-0000-0000-000000000005',
 'tmstf003-0000-0000-0000-000000000004',
 'tmstf002-0000-0000-0000-000000000003',
 'tmstf001-0000-0000-0000-000000000002',
 'tmadm000-0000-0000-0000-000000000001']
Length: 8, dtype: str

In [24]:
prefix_map = {
    "ptf": "P",
    "stf": "F",
    "adm": "M"
}

member_map = {}
for member in members:
    # remove 'tm' prefix
    id_core = member[2:8]
    # get sections
    letters = id_core[:3]
    number = id_core[3:]
    # remove leading zeros
    number = str(int(number))
    member_map[member] = prefix_map[letters] + number

print(member_map)

{'tmptf003-0000-0000-0000-000000000008': 'P3', 'tmptf002-0000-0000-0000-000000000007': 'P2', 'tmptf001-0000-0000-0000-000000000006': 'P1', 'tmstf004-0000-0000-0000-000000000005': 'F4', 'tmstf003-0000-0000-0000-000000000004': 'F3', 'tmstf002-0000-0000-0000-000000000003': 'F2', 'tmstf001-0000-0000-0000-000000000002': 'F1', 'tmadm000-0000-0000-0000-000000000001': 'M0'}

In [25]:
shifts = df['shiftTypeId'].unique()

shift_map = {}
for shift in shifts:
    # Take first 7 chars (e.g., 'stP00000')
    code = shift[:7]
    # Extract only capital letters
    letters = ''.join(re.findall(r'[A-Z]+', code))
    shift_map[shift] = letters

print(shift_map)

{'stA00000-0000-0000-0000-000000000002': 'A', 'stBB0000-0000-0000-0000-000000000004': 'BB', 'stAA0000-0000-0000-0000-000000000001': 'AA', 'stB00000-0000-0000-0000-000000000003': 'B', 'stP00000-0000-0000-0000-000000000005': 'P'}

In [26]:
df['teamMemberId'] = df['teamMemberId'].map(member_map)
df['shiftTypeId'] = df['shiftTypeId'].map(shift_map)

In [27]:
df['date'] = pd.to_datetime(df['date'])
df['date'] = df['date'].dt.tz_convert('Asia/Tokyo')
df['date'] = df['date'].dt.date
display(df)

           date teamMemberId shiftTypeId
0    2026-03-01           P3           A
1    2026-03-02           P3           A
2    2026-03-08           P3          BB
3    2026-03-09           P3          BB
4    2026-03-15           P3          AA
..          ...          ...         ...
137  2026-03-24           M0           A
138  2026-03-25           M0           A
139  2026-03-27           M0          BB
140  2026-03-28           M0          BB
141  2026-03-30           M0          BB

[142 rows x 3 columns]

In [28]:
dfs = df.sort_values(
    by=['date', 'teamMemberId', 'shiftTypeId']
).reset_index(drop=True)

display(dfs)

           date teamMemberId shiftTypeId
0    2026-03-01           F2          AA
1    2026-03-01           F4           A
2    2026-03-01           M0          BB
3    2026-03-01           P1          BB
4    2026-03-01           P2          BB
..          ...          ...         ...
137  2026-03-30           P3           B
138  2026-03-31           F1           A
139  2026-03-31           F2           A
140  2026-03-31           P1          BB
141  2026-03-31           P2           P

[142 rows x 3 columns]

In [29]:
grouped = df.groupby('date')
for date, group in grouped:
    display(group.sort_values(['teamMemberId', 'shiftTypeId']))

           date teamMemberId shiftTypeId
76   2026-03-01           F2          AA
32   2026-03-01           F4           A
120  2026-03-01           M0          BB
20   2026-03-01           P1          BB
10   2026-03-01           P2          BB
0    2026-03-01           P3           A

           date teamMemberId shiftTypeId
54   2026-03-02           F3          AA
121  2026-03-02           M0          BB
11   2026-03-02           P2          BB
1    2026-03-02           P3           A

           date teamMemberId shiftTypeId
77   2026-03-03           F2           A
55   2026-03-03           F3          AA
33   2026-03-03           F4          BB
122  2026-03-03           M0          BB

          date teamMemberId shiftTypeId
98  2026-03-04           F1          BB
56  2026-03-04           F3          AA
34  2026-03-04           F4          BB
21  2026-03-04           P1           P

           date teamMemberId shiftTypeId
99   2026-03-05           F1          BB
57   2026-03-05           F3          AA
35   2026-03-05           F4          BB
123  2026-03-05           M0          AA

           date teamMemberId shiftTypeId
100  2026-03-06           F1          BB
78   2026-03-06           F2           A
36   2026-03-06           F4          BB
124  2026-03-06           M0          AA

           date teamMemberId shiftTypeId
101  2026-03-07           F1          BB
79   2026-03-07           F2           A
58   2026-03-07           F3           A
37   2026-03-07           F4          BB
125  2026-03-07           M0          AA
22   2026-03-07           P1           P

           date teamMemberId shiftTypeId
102  2026-03-08           F1          BB
80   2026-03-08           F2           A
59   2026-03-08           F3           A
23   2026-03-08           P1           P
12   2026-03-08           P2          AA
2    2026-03-08           P3          BB

          date teamMemberId shiftTypeId
81  2026-03-09           F2           A
38  2026-03-09           F4           A
24  2026-03-09           P1           P
3   2026-03-09           P3          BB

           date teamMemberId shiftTypeId
103  2026-03-10           F1          BB
39   2026-03-10           F4           A
126  2026-03-10           M0          AA
13   2026-03-10           P2          BB

           date teamMemberId shiftTypeId
104  2026-03-11           F1          BB
82   2026-03-11           F2           A
60   2026-03-11           F3          BB
127  2026-03-11           M0          AA

           date teamMemberId shiftTypeId
105  2026-03-12           F1          BB
83   2026-03-12           F2           A
61   2026-03-12           F3          BB
40   2026-03-12           F4          AA

           date teamMemberId shiftTypeId
84   2026-03-13           F2           A
62   2026-03-13           F3          BB
41   2026-03-13           F4          AA
128  2026-03-13           M0          BB

           date teamMemberId shiftTypeId
106  2026-03-14           F1           A
85   2026-03-14           F2           A
63   2026-03-14           F3          BB
42   2026-03-14           F4          AA
129  2026-03-14           M0          BB
25   2026-03-14           P1          AA

           date teamMemberId shiftTypeId
107  2026-03-15           F1           A
86   2026-03-15           F2           A
43   2026-03-15           F4          AA
130  2026-03-15           M0          BB
14   2026-03-15           P2          BB
4    2026-03-15           P3          AA

           date teamMemberId shiftTypeId
44   2026-03-16           F4          AA
131  2026-03-16           M0          BB
26   2026-03-16           P1          AA
5    2026-03-16           P3          AA

           date teamMemberId shiftTypeId
108  2026-03-17           F1          BB
87   2026-03-17           F2           A
64   2026-03-17           F3           B
15   2026-03-17           P2          BB

           date teamMemberId shiftTypeId
88   2026-03-18           F2           A
65   2026-03-18           F3           B
45   2026-03-18           F4           A
132  2026-03-18           M0          BB

           date teamMemberId shiftTypeId
109  2026-03-19           F1          BB
66   2026-03-19           F3           B
46   2026-03-19           F4           A
133  2026-03-19           M0          BB

           date teamMemberId shiftTypeId
110  2026-03-20           F1          BB
89   2026-03-20           F2          AA
67   2026-03-20           F3           B
134  2026-03-20           M0          BB

           date teamMemberId shiftTypeId
111  2026-03-21           F1          BB
90   2026-03-21           F2          AA
68   2026-03-21           F3           B
47   2026-03-21           F4           B
135  2026-03-21           M0          BB
27   2026-03-21           P1          BB

           date teamMemberId shiftTypeId
112  2026-03-22           F1          BB
91   2026-03-22           F2          AA
48   2026-03-22           F4           B
136  2026-03-22           M0          BB
16   2026-03-22           P2          AA
6    2026-03-22           P3           B

           date teamMemberId shiftTypeId
113  2026-03-23           F1          BB
69   2026-03-23           F3           A
49   2026-03-23           F4           B
7    2026-03-23           P3           B

           date teamMemberId shiftTypeId
70   2026-03-24           F3           A
137  2026-03-24           M0           A
28   2026-03-24           P1          AA
17   2026-03-24           P2          BB

           date teamMemberId shiftTypeId
114  2026-03-25           F1           A
92   2026-03-25           F2          BB
71   2026-03-25           F3           A
138  2026-03-25           M0           A

           date teamMemberId shiftTypeId
115  2026-03-26           F1           A
93   2026-03-26           F2          BB
72   2026-03-26           F3           A
50   2026-03-26           F4          BB

           date teamMemberId shiftTypeId
116  2026-03-27           F1           A
94   2026-03-27           F2          BB
51   2026-03-27           F4          BB
139  2026-03-27           M0          BB

           date teamMemberId shiftTypeId
117  2026-03-28           F1           A
95   2026-03-28           F2          BB
73   2026-03-28           F3          AA
52   2026-03-28           F4          BB
140  2026-03-28           M0          BB
29   2026-03-28           P1           P

           date teamMemberId shiftTypeId
118  2026-03-29           F1           A
96   2026-03-29           F2          BB
74   2026-03-29           F3          AA
30   2026-03-29           P1           P
18   2026-03-29           P2          BB
8    2026-03-29           P3           B

           date teamMemberId shiftTypeId
75   2026-03-30           F3          AA
53   2026-03-30           F4           A
141  2026-03-30           M0          BB
9    2026-03-30           P3           B

           date teamMemberId shiftTypeId
119  2026-03-31           F1           A
97   2026-03-31           F2           A
31   2026-03-31           P1          BB
19   2026-03-31           P2           P

In [30]:
count_table = df.groupby('date').size().reset_index(name='count')
display(count_table)

          date  count
0   2026-03-01      6
1   2026-03-02      4
2   2026-03-03      4
3   2026-03-04      4
4   2026-03-05      4
5   2026-03-06      4
6   2026-03-07      6
7   2026-03-08      6
8   2026-03-09      4
9   2026-03-10      4
10  2026-03-11      4
11  2026-03-12      4
12  2026-03-13      4
13  2026-03-14      6
14  2026-03-15      6
15  2026-03-16      4
16  2026-03-17      4
17  2026-03-18      4
18  2026-03-19      4
19  2026-03-20      4
20  2026-03-21      6
21  2026-03-22      6
22  2026-03-23      4
23  2026-03-24      4
24  2026-03-25      4
25  2026-03-26      4
26  2026-03-27      4
27  2026-03-28      6
28  2026-03-29      6
29  2026-03-30      4
30  2026-03-31      4